#!/bin/bash
# =============================================================================
# Phase 2 End-to-End Test: C++ calling Rust device functions via LTOIR
#
# This script runs the complete pipeline:
#   1. Compile Rust NVVM IR → LTOIR (libNVVM)
#   2. Compile C++ caller kernel → LTOIR (nvcc)
#   3. Link both LTOIRs → cubin (nvJitLink)
#   4. Build C++ test runner
#   5. Run GPU tests
#
# Prerequisites:
#   - NVVM IR must be pre-generated by:
#     cargo oxide run cpp_consumes_rust_device --emit-nvvm-ir --arch=<your_arch>  # e.g., sm_120
#   - CUDA Toolkit with libNVVM, nvJitLink, nvcc
#   - LTOIR tools built (reuses device_ffi_test/tools/)
#
# Usage:
#   cd cuda-caller
#   ./run_test.sh [arch]
#   ./run_test.sh sm_120
# =============================================================================

set -e

ARCH="${1:-sm_120}"
CUDA_HOME="${CUDA_HOME:-/usr/local/cuda}"
NVCC_CCBIN="${NVCC_CCBIN:-${CUDAHOSTCXX:-}}"
NVCC_FLAGS=()
if [[ -n "$NVCC_CCBIN" ]]; then
    NVCC_FLAGS+=("-ccbin=$NVCC_CCBIN")
fi

# Paths
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
EXAMPLE_DIR="$(dirname "$SCRIPT_DIR")"
TOOLS_DIR="$EXAMPLE_DIR/../device_ffi_test/tools"

RUST_LL="$EXAMPLE_DIR/cpp_consumes_rust_device.ll"
RUST_LTOIR="$EXAMPLE_DIR/cpp_consumes_rust_device.ltoir"
CALLER_LTOIR="$SCRIPT_DIR/caller_kernel.ltoir"
MERGED_CUBIN="$EXAMPLE_DIR/merged.cubin"

echo "=== Phase 2: C++ calling Rust device functions via LTOIR ==="
echo "Arch: $ARCH"
if [[ -n "$NVCC_CCBIN" ]]; then
    echo "nvcc host compiler: $NVCC_CCBIN"
fi
echo ""

# ---- Step 0: Check prerequisites ----
if [ ! -f "$RUST_LL" ]; then
    echo "ERROR: Rust NVVM IR not found: $RUST_LL"
    echo ""
    echo "Generate it first with:"
    echo "  cargo oxide run cpp_consumes_rust_device --emit-nvvm-ir --arch=$ARCH"
    exit 1
fi

# ---- Step 1: Build LTOIR tools (if needed) ----
if [ ! -f "$TOOLS_DIR/compile_ltoir" ] || [ ! -f "$TOOLS_DIR/link_ltoir" ]; then
    echo "--- Building LTOIR tools ---"
    (cd "$TOOLS_DIR" && ./build_tools.sh)
    echo ""
fi

# ---- Step 2: Compile Rust NVVM IR → LTOIR ----
echo "--- Compiling Rust NVVM IR → LTOIR (libNVVM) ---"
"$TOOLS_DIR/compile_ltoir" "$RUST_LL" "$ARCH" "$RUST_LTOIR"
echo ""

# ---- Step 3: Compile C++ caller kernel → LTOIR ----
echo "--- Compiling C++ caller kernel → LTOIR (nvcc) ---"
COMPUTE="compute_${ARCH#sm_}"
nvcc "${NVCC_FLAGS[@]}" \
     -dc \
     --keep \
     -gencode "arch=${COMPUTE},code=lto_${ARCH#sm_}" \
     "$SCRIPT_DIR/caller_kernel.cu" \
     -o "$SCRIPT_DIR/caller_kernel.o"
echo "  ✓ caller_kernel.ltoir"
echo ""

# ---- Step 4: Link LTOIRs → cubin ----
echo "--- Linking Rust + C++ LTOIR → cubin (nvJitLink) ---"
"$TOOLS_DIR/link_ltoir" \
    "-arch=$ARCH" \
    -o "$MERGED_CUBIN" \
    "$RUST_LTOIR" \
    "$CALLER_LTOIR"
echo ""

# ---- Step 5: Build test runner ----
echo "--- Building C++ test runner ---"
nvcc "${NVCC_FLAGS[@]}" -o "$SCRIPT_DIR/test_runner" "$SCRIPT_DIR/test_runner.cu" -lcuda
echo "  ✓ test_runner built"
echo ""

# ---- Step 6: Run GPU tests ----
echo "--- Running GPU tests ---"
echo ""
"$SCRIPT_DIR/test_runner" "$MERGED_CUBIN"
