/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// Thread-local scratch is indexed by `i`; iterator form doesn't apply.
#![allow(clippy::needless_range_loop)]

//! MathDx FFI Test - cuda-oxide kernel calling MathDx (cuFFTDx, cuBLASDx) via LTOIR
//!
//! This example demonstrates calling NVIDIA MathDx device extension libraries
//! (cuFFTDx for FFT, cuBLASDx for GEMM) from cuda-oxide kernels via LTOIR linking.
//!
//! ## Prerequisites
//!
//! - **CUDA Toolkit 12.x+** with nvcc
//! - **MathDx Library** from: <https://developer.nvidia.com/cublasdx-downloads>
//!
//! ## Usage
//!
//! ```bash
//! # Build and run (this command handles the entire pipeline)
//! cargo oxide run mathdx_ffi_test --emit-nvvm-ir --arch=<your_arch>  # e.g., sm_120
//!
//! # With libmathdx feature (requires LIBMATHDX_PATH in .cargo/config.toml)
//! cargo oxide run mathdx_ffi_test --emit-nvvm-ir --arch=<your_arch> --features libmathdx  # e.g., sm_120
//! ```

use cuda_device::{device, kernel, shared::DynamicSharedArray};
use cuda_host::cuda_module;

#[cfg(feature = "libmathdx")]
use std::ffi::CString;

// =============================================================================
// cuFFTDx wrapper functions from cufftdx_wrappers.cu
//
// Thread-level FFT operations - each thread computes a complete FFT.
// =============================================================================

#[device]
unsafe extern "C" {
    // 8-point FFT
    fn cufftdx_fft_8_storage_size() -> i32;
    fn cufftdx_fft_8_elements_per_thread() -> i32;
    fn cufftdx_fft_8_c2c_f32_forward(data: *mut f32);
    fn cufftdx_fft_8_c2c_f32_inverse(data: *mut f32);

    // 16-point FFT
    fn cufftdx_fft_16_storage_size() -> i32;
    fn cufftdx_fft_16_elements_per_thread() -> i32;
    fn cufftdx_fft_16_c2c_f32_forward(data: *mut f32);
    fn cufftdx_fft_16_c2c_f32_inverse(data: *mut f32);

    // 32-point FFT
    fn cufftdx_fft_32_storage_size() -> i32;
    fn cufftdx_fft_32_c2c_f32_forward(data: *mut f32);

    // Debug function - simple array doubling to test extern pointer writes
    fn debug_extern_double_array(data: *mut f32, n: i32);
}

// =============================================================================
// cuBLASDx wrapper functions from cublasdx_wrappers.cu
//
// Block-level GEMM operations - all threads in block cooperate.
// =============================================================================

#[device]
unsafe extern "C" {
    // 32x32x32 GEMM configuration queries
    fn cublasdx_gemm_32x32x32_smem_size() -> i32;
    fn cublasdx_gemm_32x32x32_smem_size_ab() -> i32;
    fn cublasdx_gemm_32x32x32_block_dim_x() -> i32;
    fn cublasdx_gemm_32x32x32_block_dim_y() -> i32;
    fn cublasdx_gemm_32x32x32_block_dim_z() -> i32;

    // 32x32x32 GEMM execution
    fn cublasdx_gemm_32x32x32_f32(a: *const f32, b: *const f32, c: *mut f32, smem: *mut i8);
    fn cublasdx_gemm_32x32x32_f32_alphabeta(
        alpha: f32,
        a: *const f32,
        b: *const f32,
        beta: f32,
        c: *mut f32,
        smem: *mut i8,
    );
}

// =============================================================================
// libmathdx-generated FFT functions (Option B - runtime LTOIR generation)
//
// These functions are generated at build time by calling libmathdx APIs.
// The symbol names are set via COMMONDX_OPTION_SYMBOL_NAME.
// Only available when the "libmathdx" feature is enabled.
// =============================================================================

#[cfg(feature = "libmathdx")]
#[device]
unsafe extern "C" {
    /// 16-point forward FFT generated by libmathdx at build time
    /// Thread-level execution: each thread computes one FFT
    fn libmathdx_fft_16_forward(data: *mut f32);

    /// 16-point inverse FFT generated by libmathdx at build time
    fn libmathdx_fft_16_inverse(data: *mut f32);
}

// =============================================================================
// Test Kernels
// =============================================================================
#[cuda_module]
mod kernels {
    use super::*;

    /// Test kernel: 8-point FFT forward then inverse (should recover original)
    ///
    /// Each thread:
    /// 1. Loads 8 complex values from global memory into local array
    /// 2. Performs forward FFT
    /// 3. Performs inverse FFT
    /// 4. Stores result back to global memory
    ///
    /// After FFT -> IFFT, data should be scaled by FFT size (8).
    #[kernel]
    pub fn test_fft_8_roundtrip(input: *const f32, output: *mut f32) {
        let tid = cuda_device::thread::threadIdx_x() as usize;

        // Each thread processes 8 complex numbers = 16 floats
        let offset = tid * 16;

        // Local storage for FFT (8 complex = 16 floats)
        let mut local_data: [f32; 16] = [0.0; 16];

        // Load from global memory
        for i in 0..16 {
            local_data[i] = unsafe { *input.add(offset + i) };
        }

        // Forward FFT
        unsafe {
            cufftdx_fft_8_c2c_f32_forward(local_data.as_mut_ptr());
        }

        // Inverse FFT
        unsafe {
            cufftdx_fft_8_c2c_f32_inverse(local_data.as_mut_ptr());
        }

        // Store to global memory (result is scaled by N=8)
        for i in 0..16 {
            unsafe {
                *output.add(offset + i) = local_data[i];
            }
        }
    }

    /// Test kernel: 16-point FFT forward then inverse
    #[kernel]
    pub fn test_fft_16_roundtrip(input: *const f32, output: *mut f32) {
        let tid = cuda_device::thread::threadIdx_x() as usize;

        // Each thread processes 16 complex numbers = 32 floats
        let offset = tid * 32;

        // Local storage for FFT (16 complex = 32 floats)
        let mut local_data: [f32; 32] = [0.0; 32];

        // Load from global memory
        for i in 0..32 {
            local_data[i] = unsafe { *input.add(offset + i) };
        }

        // Forward FFT
        unsafe {
            cufftdx_fft_16_c2c_f32_forward(local_data.as_mut_ptr());
        }

        // Inverse FFT
        unsafe {
            cufftdx_fft_16_c2c_f32_inverse(local_data.as_mut_ptr());
        }

        // Store to global memory (result is scaled by N=16)
        for i in 0..32 {
            unsafe {
                *output.add(offset + i) = local_data[i];
            }
        }
    }

    /// Test kernel: 32x32x32 block-level GEMM
    ///
    /// C = A * B
    /// - A: 32x32 row-major
    /// - B: 32x32 col-major
    /// - C: 32x32 output
    ///
    /// All 256 threads in the block cooperate.
    #[kernel]
    pub fn test_gemm_32x32x32(a: *const f32, b: *const f32, c: *mut f32) {
        // Get shared memory for cuBLASDx
        // cuBLASDx requires specific alignment, use 128-byte alignment
        let smem: *mut i8 = DynamicSharedArray::<i8, 128>::get();

        // All threads call the GEMM function together
        unsafe {
            cublasdx_gemm_32x32x32_f32(a, b, c, smem);
        }
    }

    /// Test kernel: 32x32x32 GEMM with alpha/beta scaling
    ///
    /// C = alpha * A * B + beta * C
    #[kernel]
    pub fn test_gemm_32x32x32_alphabeta(
        alpha: f32,
        a: *const f32,
        b: *const f32,
        beta: f32,
        c: *mut f32,
    ) {
        let smem: *mut i8 = DynamicSharedArray::<i8, 128>::get();

        unsafe {
            cublasdx_gemm_32x32x32_f32_alphabeta(alpha, a, b, beta, c, smem);
        }
    }

    /// Debug kernel: Copy through local array using as_mut_ptr()
    /// This tests if the as_mut_ptr() path works correctly for memory-backed arrays.
    #[kernel]
    pub fn debug_copy_through_local(input: *const f32, output: *mut f32) {
        let tid = cuda_device::thread::threadIdx_x() as usize;
        let offset = tid * 16;

        // Local storage (same as FFT-8 test)
        let mut local_data: [f32; 16] = [0.0; 16];

        // Load from global memory using runtime index (triggers memory-backing)
        for i in 0..16 {
            local_data[i] = unsafe { *input.add(offset + i) };
        }

        // Get pointer via as_mut_ptr() - THIS IS WHAT WE'RE TESTING
        let ptr = local_data.as_mut_ptr();

        // Use the pointer to read/write (simulating what FFT would do)
        // Just double each value through the pointer
        for i in 0..16 {
            unsafe {
                let val = *ptr.add(i);
                *ptr.add(i) = val * 2.0;
            }
        }

        // Store to global memory using runtime index
        for i in 0..16 {
            unsafe {
                *output.add(offset + i) = local_data[i];
            }
        }
    }

    /// Debug kernel: Test extern function that writes through a pointer
    /// This tests if extern functions can modify data through pointer arguments.
    #[kernel]
    pub fn debug_extern_double(input: *const f32, output: *mut f32) {
        let tid = cuda_device::thread::threadIdx_x() as usize;
        let offset = tid * 16;

        // Local storage
        let mut local_data: [f32; 16] = [0.0; 16];

        // Load from global memory
        for i in 0..16 {
            local_data[i] = unsafe { *input.add(offset + i) };
        }

        // Call EXTERN function to double the values via as_mut_ptr()
        unsafe {
            debug_extern_double_array(local_data.as_mut_ptr(), 16);
        }

        // Store to global memory
        for i in 0..16 {
            unsafe {
                *output.add(offset + i) = local_data[i];
            }
        }
    }

    /// Debug kernel: Test extern function that writes through GLOBAL memory pointer
    /// This tests if the issue is specific to local memory vs global memory.
    #[kernel]
    pub fn debug_extern_double_global(inout: *mut f32) {
        let tid = cuda_device::thread::threadIdx_x() as usize;
        let offset = tid * 16;

        // Call EXTERN function directly on GLOBAL memory pointer
        unsafe {
            debug_extern_double_array(inout.add(offset), 16);
        }
    }

    /// Query kernel: Get cuFFTDx configuration values
    #[kernel]
    pub fn query_fft_config(output: *mut i32) {
        let tid = cuda_device::thread::threadIdx_x();
        if tid == 0 {
            unsafe {
                // FFT-8 config
                *output.add(0) = cufftdx_fft_8_storage_size();
                *output.add(1) = cufftdx_fft_8_elements_per_thread();

                // FFT-16 config
                *output.add(2) = cufftdx_fft_16_storage_size();
                *output.add(3) = cufftdx_fft_16_elements_per_thread();

                // FFT-32 config
                *output.add(4) = cufftdx_fft_32_storage_size();
            }
        }
    }

    /// Query kernel: Get cuBLASDx configuration values
    #[kernel]
    pub fn query_gemm_config(output: *mut i32) {
        let tid = cuda_device::thread::threadIdx_x();
        if tid == 0 {
            unsafe {
                *output.add(0) = cublasdx_gemm_32x32x32_smem_size();
                *output.add(1) = cublasdx_gemm_32x32x32_smem_size_ab();
                *output.add(2) = cublasdx_gemm_32x32x32_block_dim_x();
                *output.add(3) = cublasdx_gemm_32x32x32_block_dim_y();
                *output.add(4) = cublasdx_gemm_32x32x32_block_dim_z();
            }
        }
    }

    // =============================================================================
    // libmathdx-generated FFT Test Kernels (Option B)
    // Only available when the "libmathdx" feature is enabled.
    // =============================================================================

    /// Test kernel: 16-point FFT using libmathdx-generated LTOIR
    ///
    /// Uses functions generated at build time via libmathdx C API.
    /// This demonstrates "Option B" - no hand-written C++ wrappers needed.
    #[cfg(feature = "libmathdx")]
    #[kernel]
    pub fn test_libmathdx_fft_16_roundtrip(input: *const f32, output: *mut f32) {
        let tid = cuda_device::thread::threadIdx_x() as usize;

        // Each thread processes 16 complex numbers = 32 floats
        let offset = tid * 32;

        // Local storage for FFT (16 complex = 32 floats)
        let mut local_data: [f32; 32] = [0.0; 32];

        // Load from global memory
        for i in 0..32 {
            local_data[i] = unsafe { *input.add(offset + i) };
        }

        // Forward FFT using libmathdx-generated function
        unsafe {
            libmathdx_fft_16_forward(local_data.as_mut_ptr());
        }

        // Inverse FFT using libmathdx-generated function
        unsafe {
            libmathdx_fft_16_inverse(local_data.as_mut_ptr());
        }

        // Store to global memory (result is scaled by N=16)
        for i in 0..32 {
            unsafe {
                *output.add(offset + i) = local_data[i];
            }
        }
    }
}

// =============================================================================
// Build Pipeline
//
// These functions automate the LTOIR build process:
// 1. Build C tools (compile_ltoir, link_ltoir) if not present
// 2. Build external CUDA C++ to LTOIR if sources changed
// 3. Generate libmathdx LTOIR (Option B - no C++ wrappers needed)
// 4. Compile cuda-oxide LLVM IR to LTOIR
// 5. Link all LTOIR files into a cubin
// =============================================================================

use std::path::Path;
use std::process::Command;

// =============================================================================
// libmathdx LTOIR Generation (Option B)
//
// This module demonstrates using libmathdx-sys to generate LTOIR at build time
// without writing any C++ wrapper code. The key steps are:
// 1. Create a descriptor for the operation (FFT, GEMM, etc.)
// 2. Set operators (size, precision, direction, SM, etc.)
// 3. Set a custom symbol name via COMMONDX_OPTION_SYMBOL_NAME
// 4. Finalize and extract LTOIR bytes
//
// Only available when the "libmathdx" feature is enabled.
// =============================================================================

/// Generates LTOIR for FFT operations using libmathdx C API.
/// Returns the paths to the generated LTOIR files.
#[cfg(feature = "libmathdx")]
fn generate_libmathdx_ltoir(example_dir: &Path) -> Result<Vec<std::path::PathBuf>, String> {
    use libmathdx_sys::*;

    let fwd_path = example_dir.join("libmathdx_fft_fwd.ltoir");
    let inv_path = example_dir.join("libmathdx_fft_inv.ltoir");

    // Skip if LTOIR already exists (for faster iteration)
    // Remove this check to always regenerate
    if fwd_path.exists() && inv_path.exists() {
        println!("  (using cached libmathdx LTOIR)");
        return Ok(vec![fwd_path, inv_path]);
    }

    println!("=== Generating libmathdx LTOIR ===");
    println!("    Using libmathdx C API (no C++ wrappers needed)");

    // Extract SM number from arch() (e.g., "sm_120" -> 1200)
    let arch_str = arch();
    let sm_num: i64 = arch_str
        .strip_prefix("sm_")
        .and_then(|s| s.parse::<i64>().ok())
        .map(|n| n * 10) // sm_120 -> 1200
        .ok_or_else(|| format!("Invalid ARCH format: {}", arch_str))?;

    unsafe {
        // Create a code handle to collect all generated LTOIR
        let mut code: commondxCode = 0;
        let status = commondxCreateCode(&mut code);
        if status != commondxStatusType_t_COMMONDX_SUCCESS {
            return Err(format!("Failed to create code handle: {:?}", status));
        }

        // Set target SM for code generation
        commondxSetCodeOptionInt64(code, commondxOption_t_COMMONDX_OPTION_TARGET_SM, sm_num);

        // Set code container to LTOIR
        commondxSetCodeOptionInt64(
            code,
            commondxOption_t_COMMONDX_OPTION_CODE_CONTAINER,
            commondxCodeContainer_t_COMMONDX_CODE_CONTAINER_LTOIR as i64,
        );

        // Generate Forward FFT descriptor
        let mut fft_fwd: cufftdxDescriptor = 0;
        cufftdxCreateDescriptor(&mut fft_fwd);

        // Configure 16-point C2C forward FFT
        cufftdxSetOperatorInt64(fft_fwd, cufftdxOperatorType_t_CUFFTDX_OPERATOR_SIZE, 16);
        cufftdxSetOperatorInt64(
            fft_fwd,
            cufftdxOperatorType_t_CUFFTDX_OPERATOR_TYPE,
            cufftdxType_t_CUFFTDX_TYPE_C2C as i64,
        );
        cufftdxSetOperatorInt64(
            fft_fwd,
            cufftdxOperatorType_t_CUFFTDX_OPERATOR_DIRECTION,
            cufftdxDirection_t_CUFFTDX_DIRECTION_FORWARD as i64,
        );
        cufftdxSetOperatorInt64(
            fft_fwd,
            cufftdxOperatorType_t_CUFFTDX_OPERATOR_PRECISION,
            commondxPrecision_t_COMMONDX_PRECISION_F32 as i64,
        );
        cufftdxSetOperatorInt64(fft_fwd, cufftdxOperatorType_t_CUFFTDX_OPERATOR_SM, sm_num);
        cufftdxSetOperatorInt64(
            fft_fwd,
            cufftdxOperatorType_t_CUFFTDX_OPERATOR_EXECUTION,
            commondxExecution_t_COMMONDX_EXECUTION_THREAD as i64,
        );
        cufftdxSetOperatorInt64(
            fft_fwd,
            cufftdxOperatorType_t_CUFFTDX_OPERATOR_API,
            cufftdxApi_t_CUFFTDX_API_LMEM as i64,
        );

        // Set custom symbol name (Option B key step!)
        let fwd_name = CString::new("libmathdx_fft_16_forward").unwrap();
        cufftdxSetOptionStr(
            fft_fwd,
            commondxOption_t_COMMONDX_OPTION_SYMBOL_NAME,
            fwd_name.as_ptr(),
        );

        // Generate Inverse FFT descriptor
        let mut fft_inv: cufftdxDescriptor = 0;
        cufftdxCreateDescriptor(&mut fft_inv);

        // Configure 16-point C2C inverse FFT (same as forward, just different direction)
        cufftdxSetOperatorInt64(fft_inv, cufftdxOperatorType_t_CUFFTDX_OPERATOR_SIZE, 16);
        cufftdxSetOperatorInt64(
            fft_inv,
            cufftdxOperatorType_t_CUFFTDX_OPERATOR_TYPE,
            cufftdxType_t_CUFFTDX_TYPE_C2C as i64,
        );
        cufftdxSetOperatorInt64(
            fft_inv,
            cufftdxOperatorType_t_CUFFTDX_OPERATOR_DIRECTION,
            cufftdxDirection_t_CUFFTDX_DIRECTION_INVERSE as i64,
        );
        cufftdxSetOperatorInt64(
            fft_inv,
            cufftdxOperatorType_t_CUFFTDX_OPERATOR_PRECISION,
            commondxPrecision_t_COMMONDX_PRECISION_F32 as i64,
        );
        cufftdxSetOperatorInt64(fft_inv, cufftdxOperatorType_t_CUFFTDX_OPERATOR_SM, sm_num);
        cufftdxSetOperatorInt64(
            fft_inv,
            cufftdxOperatorType_t_CUFFTDX_OPERATOR_EXECUTION,
            commondxExecution_t_COMMONDX_EXECUTION_THREAD as i64,
        );
        cufftdxSetOperatorInt64(
            fft_inv,
            cufftdxOperatorType_t_CUFFTDX_OPERATOR_API,
            cufftdxApi_t_CUFFTDX_API_LMEM as i64,
        );

        // Set custom symbol name for inverse
        let inv_name = CString::new("libmathdx_fft_16_inverse").unwrap();
        cufftdxSetOptionStr(
            fft_inv,
            commondxOption_t_COMMONDX_OPTION_SYMBOL_NAME,
            inv_name.as_ptr(),
        );

        // Finalize forward FFT descriptor into the code handle
        let status = cufftdxFinalizeCode(code, fft_fwd);
        if status != commondxStatusType_t_COMMONDX_SUCCESS {
            cufftdxDestroyDescriptor(fft_fwd);
            cufftdxDestroyDescriptor(fft_inv);
            commondxDestroyCode(code);
            return Err(format!("Failed to finalize forward FFT: {:?}", status));
        }
        cufftdxDestroyDescriptor(fft_fwd);

        // Create a second code handle for inverse FFT
        // (libmathdx may not support multiple descriptors in one code handle)
        let mut code_inv: commondxCode = 0;
        let status = commondxCreateCode(&mut code_inv);
        if status != commondxStatusType_t_COMMONDX_SUCCESS {
            cufftdxDestroyDescriptor(fft_inv);
            commondxDestroyCode(code);
            return Err(format!(
                "Failed to create inverse code handle: {:?}",
                status
            ));
        }
        commondxSetCodeOptionInt64(code_inv, commondxOption_t_COMMONDX_OPTION_TARGET_SM, sm_num);
        commondxSetCodeOptionInt64(
            code_inv,
            commondxOption_t_COMMONDX_OPTION_CODE_CONTAINER,
            commondxCodeContainer_t_COMMONDX_CODE_CONTAINER_LTOIR as i64,
        );

        let status = cufftdxFinalizeCode(code_inv, fft_inv);
        if status != commondxStatusType_t_COMMONDX_SUCCESS {
            cufftdxDestroyDescriptor(fft_inv);
            commondxDestroyCode(code);
            commondxDestroyCode(code_inv);
            return Err(format!("Failed to finalize inverse FFT: {:?}", status));
        }
        cufftdxDestroyDescriptor(fft_inv);

        // Get LTOIR from forward FFT code handle
        let mut ltoir_fwd_size: usize = 0;
        let status = commondxGetCodeLTOIRSize(code, &mut ltoir_fwd_size);
        if status != commondxStatusType_t_COMMONDX_SUCCESS {
            commondxDestroyCode(code);
            commondxDestroyCode(code_inv);
            return Err(format!("Failed to get forward LTOIR size: {:?}", status));
        }

        let mut ltoir_fwd_data = vec![0u8; ltoir_fwd_size];
        let status = commondxGetCodeLTOIR(
            code,
            ltoir_fwd_size,
            ltoir_fwd_data.as_mut_ptr() as *mut std::ffi::c_void,
        );
        if status != commondxStatusType_t_COMMONDX_SUCCESS {
            commondxDestroyCode(code);
            commondxDestroyCode(code_inv);
            return Err(format!("Failed to get forward LTOIR: {:?}", status));
        }

        // Get LTOIR from inverse FFT code handle
        let mut ltoir_inv_size: usize = 0;
        let status = commondxGetCodeLTOIRSize(code_inv, &mut ltoir_inv_size);
        if status != commondxStatusType_t_COMMONDX_SUCCESS {
            commondxDestroyCode(code);
            commondxDestroyCode(code_inv);
            return Err(format!("Failed to get inverse LTOIR size: {:?}", status));
        }

        let mut ltoir_inv_data = vec![0u8; ltoir_inv_size];
        let status = commondxGetCodeLTOIR(
            code_inv,
            ltoir_inv_size,
            ltoir_inv_data.as_mut_ptr() as *mut std::ffi::c_void,
        );
        if status != commondxStatusType_t_COMMONDX_SUCCESS {
            commondxDestroyCode(code);
            commondxDestroyCode(code_inv);
            return Err(format!("Failed to get inverse LTOIR: {:?}", status));
        }

        // Write both LTOIRs to separate files
        std::fs::write(&fwd_path, &ltoir_fwd_data)
            .map_err(|e| format!("Failed to write forward LTOIR: {}", e))?;
        std::fs::write(&inv_path, &ltoir_inv_data)
            .map_err(|e| format!("Failed to write inverse LTOIR: {}", e))?;

        println!(
            "    Generated {} bytes (forward) + {} bytes (inverse)",
            ltoir_fwd_size, ltoir_inv_size
        );
        println!("    Symbols: libmathdx_fft_16_forward, libmathdx_fft_16_inverse");
        println!("  ✓ libmathdx LTOIR generated\n");

        // Cleanup
        commondxDestroyCode(code);
        commondxDestroyCode(code_inv);
    }

    Ok(vec![fwd_path, inv_path])
}

/// Target GPU architecture for LTOIR compilation and linking.
///
/// Reads `CUDA_OXIDE_TARGET` (set by `cargo oxide run --arch=...`), falling
/// back to `sm_120`. Leaking the string keeps a `&'static str` interface
/// matching the rest of the example.
fn arch() -> &'static str {
    if let Ok(target) = std::env::var("CUDA_OXIDE_TARGET") {
        return Box::leak(target.into_boxed_str());
    }
    "sm_120"
}

/// Returns the path to this example's directory (where Cargo.toml lives).
fn get_example_dir() -> std::path::PathBuf {
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    Path::new(manifest_dir).to_path_buf()
}

/// Runs a shell command in the specified directory.
fn run_command(cmd: &str, args: &[&str], cwd: &Path) -> Result<(), String> {
    run_command_with_env(cmd, args, cwd, &[])
}

/// Same as `run_command`, but injects extra `(key, value)` pairs into the
/// child's environment first. Used to forward the discovered `MATHDX_ROOT`
/// to `extern-libs/build.sh` even when the parent shell didn't export it.
fn run_command_with_env(
    cmd: &str,
    args: &[&str],
    cwd: &Path,
    extra_env: &[(&str, &str)],
) -> Result<(), String> {
    let mut command = Command::new(cmd);
    command.args(args).current_dir(cwd);
    for (k, v) in extra_env {
        command.env(k, v);
    }
    let status = command
        .status()
        .map_err(|e| format!("Failed to run {}: {}", cmd, e))?;

    if status.success() {
        Ok(())
    } else {
        Err(format!("{} failed with exit code {:?}", cmd, status.code()))
    }
}

/// Checks if a target file needs to be rebuilt based on source file timestamps.
fn file_needs_rebuild(target: &Path, sources: &[&Path]) -> bool {
    if !target.exists() {
        return true;
    }
    let target_time = target.metadata().and_then(|m| m.modified()).ok();
    for src in sources {
        if let Ok(src_time) = src.metadata().and_then(|m| m.modified())
            && target_time.map(|t| src_time > t).unwrap_or(true)
        {
            return true;
        }
    }
    false
}

/// Builds the LTOIR tools (compile_ltoir, link_ltoir) if they don't exist.
fn build_tools(example_dir: &Path) -> Result<(), String> {
    let tools_dir = example_dir.join("tools");
    let compile_ltoir = tools_dir.join("compile_ltoir");
    let link_ltoir = tools_dir.join("link_ltoir");

    if compile_ltoir.exists() && link_ltoir.exists() {
        return Ok(());
    }

    println!("=== Building LTOIR tools ===");
    run_command("./build_tools.sh", &[], &tools_dir)?;
    println!("  ✓ Tools built\n");
    Ok(())
}

/// Builds external MathDx CUDA C++ files to LTOIR.
/// Always does a clean rebuild during development.
fn build_external_ltoir(example_dir: &Path, mathdx_root: &Path) -> Result<(), String> {
    let extern_libs_dir = example_dir.join("extern-libs");

    println!("=== Building MathDx LTOIR ===");
    println!("    Using MATHDX_ROOT={}", mathdx_root.display());
    let mathdx_root_str = mathdx_root
        .to_str()
        .ok_or_else(|| format!("MATHDX_ROOT is not valid UTF-8: {}", mathdx_root.display()))?;
    // Always clean rebuild during development to ensure fresh LTOIR
    run_command_with_env(
        "./build.sh",
        &["--clean", arch()],
        &extern_libs_dir,
        &[("MATHDX_ROOT", mathdx_root_str)],
    )?;
    println!("  ✓ MathDx LTOIR built\n");
    Ok(())
}

/// Compiles cuda-oxide LLVM IR (.ll) to LTOIR using libNVVM.
fn compile_cuda_oxide_ltoir(example_dir: &Path) -> Result<(), String> {
    let ll_file = example_dir.join("mathdx_ffi_test.ll");
    let ltoir_file = example_dir.join("mathdx_ffi_test.ltoir");
    let tools_dir = example_dir.join("tools");

    if !ll_file.exists() {
        return Err(format!(
            "cuda-oxide LLVM IR not found: {}\n\
             Run: cargo oxide run mathdx_ffi_test --emit-nvvm-ir --arch={}",
            ll_file.display(),
            arch()
        ));
    }

    if !file_needs_rebuild(&ltoir_file, &[&ll_file]) {
        return Ok(());
    }

    println!("=== Compiling cuda-oxide LLVM IR to LTOIR ===");
    run_command(
        "./compile_ltoir",
        &[
            ll_file.to_str().unwrap(),
            arch(),
            ltoir_file.to_str().unwrap(),
        ],
        &tools_dir,
    )?;
    println!("  ✓ cuda-oxide LTOIR compiled\n");
    Ok(())
}

/// Links all LTOIR files into a single cubin using nvJitLink.
/// Includes: cuda-oxide, MathDx C++ wrappers, and optionally libmathdx-generated LTOIR.
fn link_ltoir(
    example_dir: &Path,
    libmathdx_ltoirs: &[std::path::PathBuf],
) -> Result<std::path::PathBuf, String> {
    let tools_dir = example_dir.join("tools");
    let extern_libs_dir = example_dir.join("extern-libs");
    let cubin_file = example_dir.join("merged.cubin");
    let cuda_oxide_ltoir = example_dir.join("mathdx_ffi_test.ltoir");
    let cufftdx_ltoir = extern_libs_dir.join("cufftdx_wrappers.ltoir");
    let cublasdx_ltoir = extern_libs_dir.join("cublasdx_wrappers.ltoir");

    // Build list of LTOIR sources for dependency checking
    let mut sources: Vec<&Path> = vec![
        cuda_oxide_ltoir.as_path(),
        cufftdx_ltoir.as_path(),
        cublasdx_ltoir.as_path(),
    ];
    for ltoir in libmathdx_ltoirs {
        sources.push(ltoir.as_path());
    }

    if !file_needs_rebuild(&cubin_file, &sources) {
        return Ok(cubin_file);
    }

    println!("=== Linking LTOIR files ===");
    println!("    Sources:");
    println!("      - cuda-oxide: {}", cuda_oxide_ltoir.display());
    println!("      - cuFFTDx wrappers: {}", cufftdx_ltoir.display());
    println!("      - cuBLASDx wrappers: {}", cublasdx_ltoir.display());
    for ltoir in libmathdx_ltoirs {
        println!("      - libmathdx generated: {}", ltoir.display());
    }

    // Build command arguments - collect strings to extend lifetimes
    let arch_arg = format!("-arch={}", arch());
    let cubin_str = cubin_file.to_str().unwrap().to_string();
    let cuda_oxide_str = cuda_oxide_ltoir.to_str().unwrap().to_string();
    let cufftdx_str = cufftdx_ltoir.to_str().unwrap().to_string();
    let cublasdx_str = cublasdx_ltoir.to_str().unwrap().to_string();
    let libmathdx_strs: Vec<String> = libmathdx_ltoirs
        .iter()
        .map(|p| p.to_str().unwrap().to_string())
        .collect();

    let mut args: Vec<&str> = vec![
        &arch_arg,
        "-o",
        &cubin_str,
        &cuda_oxide_str,
        &cufftdx_str,
        &cublasdx_str,
    ];
    for s in &libmathdx_strs {
        args.push(s);
    }

    run_command("./link_ltoir", &args, &tools_dir)?;
    println!("  ✓ LTOIR linked to cubin\n");
    Ok(cubin_file)
}

/// Runs the complete build pipeline.
fn build_pipeline(mathdx_root: &Path) -> Result<std::path::PathBuf, String> {
    let example_dir = get_example_dir();

    build_tools(&example_dir)?;
    build_external_ltoir(&example_dir, mathdx_root)?;

    // Generate LTOIR using libmathdx C API (Option B) - only if feature enabled
    #[cfg(feature = "libmathdx")]
    let libmathdx_ltoirs = generate_libmathdx_ltoir(&example_dir)?;
    #[cfg(not(feature = "libmathdx"))]
    let libmathdx_ltoirs: Vec<std::path::PathBuf> = Vec::new();

    compile_cuda_oxide_ltoir(&example_dir)?;
    link_ltoir(&example_dir, &libmathdx_ltoirs)
}

// =============================================================================
// Host-side test infrastructure
// =============================================================================

use cuda_core::{CudaContext, DeviceBuffer, LaunchConfig};
use std::sync::Arc;

/// Locate a usable MathDx SDK root. A directory is *usable* iff it contains
/// both `include/` (cufftdx.hpp, cublasdx.hpp, ...) and
/// `external/cutlass/include/` — the two trees `extern-libs/build.sh` will
/// pass to `nvcc -I`. Anything less complete returns `None` so the example
/// skips cleanly instead of letting `nvcc` crash later with a "missing
/// folder" diagnostic against a half-installed or stale root.
///
/// Search order:
///   1. `MATHDX_ROOT` (explicit override; treated as the path itself).
///   2. The canonical Linux install paths used by the deb/rpm packages.
///   3. Common unpacked layouts under user/system roots — the SDK tarballs
///      extract to `<parent>/nvidia/mathdx/<version>/`, so we walk the
///      `<version>/` entries of the first `nvidia/mathdx/` we find.
///
/// This is best-effort discovery for local dev machines. The smoketest only
/// cares that we land on a usable root *or* return `None` cleanly.
fn find_mathdx_root() -> Option<std::path::PathBuf> {
    let usable = |p: &std::path::Path| -> bool {
        p.is_dir()
            && p.join("include").is_dir()
            && p.join("external").join("cutlass").join("include").is_dir()
    };

    if let Ok(root) = std::env::var("MATHDX_ROOT") {
        let p = std::path::PathBuf::from(root);
        if usable(&p) {
            return Some(p);
        }
    }

    for candidate in ["/usr/local/mathdx", "/opt/nvidia/mathdx"] {
        let p = std::path::PathBuf::from(candidate);
        if usable(&p) {
            return Some(p);
        }
    }

    // Tarball layout: `<parent>/nvidia/mathdx/<version>/`. Pick the
    // lexicographically-greatest version (usually the newest).
    let home = std::env::var_os("HOME").map(std::path::PathBuf::from);
    let mut parents: Vec<std::path::PathBuf> = vec![
        std::path::PathBuf::from("/opt"),
        std::path::PathBuf::from("/usr/local"),
    ];
    if let Some(h) = home {
        parents.push(h.join("dev"));
        parents.push(h.clone());
        parents.push(h.join(".local"));
    }

    for parent in &parents {
        if let Some(p) = pick_mathdx_under(parent, &usable) {
            return Some(p);
        }
    }

    None
}

/// Walks `<parent>` looking for a `nvidia/mathdx/<version>/` tree (either
/// directly, or one level deeper — the tarball expands to
/// `nvidia-mathdx-<...>/nvidia/mathdx/<version>/`). Returns the highest-named
/// version that satisfies `usable`.
fn pick_mathdx_under(
    parent: &std::path::Path,
    usable: &dyn Fn(&std::path::Path) -> bool,
) -> Option<std::path::PathBuf> {
    let candidates = [
        parent.join("nvidia").join("mathdx"),
        // Try one level down for unpacked tarballs.
        // We only look at entries whose name starts with `nvidia-mathdx`.
    ];

    let mut roots: Vec<std::path::PathBuf> = Vec::new();
    for c in candidates {
        if c.is_dir() {
            roots.push(c);
        }
    }
    if let Ok(entries) = std::fs::read_dir(parent) {
        for entry in entries.flatten() {
            let name = entry.file_name();
            let name_str = name.to_string_lossy();
            if name_str.starts_with("nvidia-mathdx") {
                let inner = entry.path().join("nvidia").join("mathdx");
                if inner.is_dir() {
                    roots.push(inner);
                }
            }
        }
    }

    let mut best: Option<std::path::PathBuf> = None;
    let mut best_name: Option<std::ffi::OsString> = None;
    for root in roots {
        if let Ok(versions) = std::fs::read_dir(&root) {
            for v in versions.flatten() {
                let path = v.path();
                if !usable(&path) {
                    continue;
                }
                let name = v.file_name();
                if best_name.as_ref().is_none_or(|cur| &name > cur) {
                    best = Some(path);
                    best_name = Some(name);
                }
            }
        }
    }
    best
}

fn main() {
    println!("=== MathDx FFI Test ===\n");

    // Preflight: skip cleanly if the MathDx SDK is not available on this
    // host. The smoketest's LTOIR verdict recognises the `skipping:` prefix
    // and treats this as PASS so long as the cuda-oxide NVVM IR (.ll) was
    // generated (which happens before `cargo run` is invoked).
    let mathdx_root = match find_mathdx_root() {
        Some(p) => p,
        None => {
            println!("skipping: MathDx SDK not found");
            println!();
            println!("To run this example, either:");
            println!("  - set MATHDX_ROOT to your MathDx install root, or");
            println!("  - install MathDx to /usr/local/mathdx or /opt/nvidia/mathdx, or");
            println!("  - extract the SDK tarball under ~/dev, /opt, or /usr/local — the");
            println!("    example auto-discovers `nvidia/mathdx/<version>/` trees there.");
            println!();
            println!("Download MathDx from: https://developer.nvidia.com/cublasdx-downloads");
            return;
        }
    };
    println!("MathDx root: {}\n", mathdx_root.display());

    // Build pipeline (tools, external LTOIR, link)
    let cubin_path = match build_pipeline(&mathdx_root) {
        Ok(path) => path,
        Err(e) => {
            eprintln!("Build failed: {}", e);
            std::process::exit(1);
        }
    };

    // Load and run tests
    println!("=== Running GPU Tests ===");
    let cubin_size = std::fs::metadata(&cubin_path)
        .expect("Failed to stat cubin file")
        .len();
    println!("Cubin: {} ({} bytes)", cubin_path.display(), cubin_size);

    let ctx = CudaContext::new(0).expect("Failed to create CUDA context");
    println!("Device ordinal: {}\n", ctx.ordinal());

    let module = ctx
        .load_module_from_file(cubin_path.to_str().expect("cubin path must be valid UTF-8"))
        .expect("Failed to load cubin module");
    let module = kernels::from_module(module).expect("Failed to initialize typed CUDA module");

    let mut passed = 0i32;
    let mut failed = 0i32;

    // Run tests
    test_fft_config_query(&ctx, &module, &mut passed, &mut failed);
    test_gemm_config_query(&ctx, &module, &mut passed, &mut failed);
    debug_copy_through_local_runner(&ctx, &module, &mut passed, &mut failed);
    debug_extern_double_global_runner(&ctx, &module, &mut passed, &mut failed);
    debug_extern_double_runner(&ctx, &module, &mut passed, &mut failed);

    test_fft_8_roundtrip_runner(&ctx, &module, &mut passed, &mut failed);
    test_fft_16_roundtrip_runner(&ctx, &module, &mut passed, &mut failed);
    test_gemm_32x32x32_runner(&ctx, &module, &mut passed, &mut failed);
    test_gemm_32x32x32_alphabeta_runner(&ctx, &module, &mut passed, &mut failed);

    // Option B: libmathdx-generated FFT test (no C++ wrappers!)
    // Only available with --features libmathdx
    #[cfg(feature = "libmathdx")]
    test_libmathdx_fft_16_roundtrip_runner(&ctx, &module, &mut passed, &mut failed);

    // Summary
    println!("\n=== Summary ===");
    println!("Passed: {}", passed);
    println!("Failed: {}", failed);

    if failed == 0 && passed > 0 {
        println!("\n✓ All tests PASSED!");
    } else if passed == 0 {
        println!("\nNo tests ran (kernels not found in cubin)");
        std::process::exit(1);
    } else {
        println!("\n✗ Some tests FAILED");
        std::process::exit(1);
    }
}

// =============================================================================
// Test Runner Functions
// =============================================================================

fn test_fft_config_query(
    ctx: &Arc<CudaContext>,
    module: &kernels::LoadedModule,
    passed: &mut i32,
    failed: &mut i32,
) {
    println!("--- Test: query_fft_config ---");
    println!("    Querying cuFFTDx configuration values");

    let stream = ctx.default_stream();
    let d_output = DeviceBuffer::<i32>::zeroed(&stream, 8).unwrap();

    let config = LaunchConfig {
        grid_dim: (1, 1, 1),
        block_dim: (1, 1, 1),
        shared_mem_bytes: 0,
    };

    let output_ptr = d_output.cu_deviceptr() as *mut i32;
    module
        .query_fft_config((stream).as_ref(), config, output_ptr)
        .expect("Kernel launch failed");

    let h_output = d_output.to_host_vec(&stream).unwrap();

    println!(
        "    FFT-8:  storage_size={}, elements_per_thread={}",
        h_output[0], h_output[1]
    );
    println!(
        "    FFT-16: storage_size={}, elements_per_thread={}",
        h_output[2], h_output[3]
    );
    println!("    FFT-32: storage_size={}", h_output[4]);

    // Basic validation: values should be positive
    if h_output[0] > 0 && h_output[2] > 0 && h_output[4] > 0 {
        println!("    ✓ PASSED");
        *passed += 1;
    } else {
        println!("    ✗ FAILED (invalid config values)");
        *failed += 1;
    }
}

fn test_gemm_config_query(
    ctx: &Arc<CudaContext>,
    module: &kernels::LoadedModule,
    passed: &mut i32,
    failed: &mut i32,
) {
    println!("--- Test: query_gemm_config ---");
    println!("    Querying cuBLASDx configuration values");

    let stream = ctx.default_stream();
    let d_output = DeviceBuffer::<i32>::zeroed(&stream, 8).unwrap();

    let config = LaunchConfig {
        grid_dim: (1, 1, 1),
        block_dim: (1, 1, 1),
        shared_mem_bytes: 0,
    };

    let output_ptr = d_output.cu_deviceptr() as *mut i32;
    module
        .query_gemm_config((stream).as_ref(), config, output_ptr)
        .expect("Kernel launch failed");

    let h_output = d_output.to_host_vec(&stream).unwrap();

    println!("    GEMM 32x32x32:");
    println!(
        "      smem_size={}, smem_size_ab={}",
        h_output[0], h_output[1]
    );
    println!(
        "      block_dim=({}, {}, {})",
        h_output[2], h_output[3], h_output[4]
    );

    // Validation: smem sizes should be positive, block_dim.x should be 256
    if h_output[0] > 0 && h_output[1] > 0 && h_output[2] == 256 {
        println!("    ✓ PASSED");
        *passed += 1;
    } else {
        println!("    ✗ FAILED (unexpected config values)");
        *failed += 1;
    }
}

fn debug_copy_through_local_runner(
    ctx: &Arc<CudaContext>,
    module: &kernels::LoadedModule,
    passed: &mut i32,
    failed: &mut i32,
) {
    println!("--- Test: debug_copy_through_local ---");
    println!("    Testing as_mut_ptr() on local array (doubles values)");

    let num_threads = 4usize;
    let floats_per_thread = 16usize;
    let total_floats = num_threads * floats_per_thread;

    // Generate test input: simple pattern
    let h_input: Vec<f32> = (0..total_floats)
        .map(|i| (i % floats_per_thread) as f32)
        .collect();

    let stream = ctx.default_stream();
    let d_input = DeviceBuffer::from_host(&stream, &h_input).unwrap();
    let d_output = DeviceBuffer::<f32>::zeroed(&stream, total_floats).unwrap();

    let config = LaunchConfig {
        grid_dim: (1, 1, 1),
        block_dim: (num_threads as u32, 1, 1),
        shared_mem_bytes: 0,
    };

    let input_ptr = d_input.cu_deviceptr() as *const f32;
    let output_ptr = d_output.cu_deviceptr() as *mut f32;
    module
        .debug_copy_through_local((stream).as_ref(), config, input_ptr, output_ptr)
        .expect("Kernel launch failed");

    let h_output = d_output.to_host_vec(&stream).unwrap();

    // Output should be input * 2 (kernel doubles each value via as_mut_ptr)
    let mut max_error = 0.0f32;
    for i in 0..total_floats {
        let expected = h_input[i] * 2.0;
        let error = (h_output[i] - expected).abs();
        if error > max_error {
            max_error = error;
        }
    }

    let tolerance = 1e-6;
    if max_error < tolerance {
        println!("    ✓ PASSED (max_error={:.6})", max_error);
        *passed += 1;
    } else {
        println!("    ✗ FAILED (max_error={:.6})", max_error);
        println!(
            "    First few values: input={:?}, output={:?}",
            &h_input[0..4],
            &h_output[0..4]
        );
        println!(
            "    Expected (input*2): {:?}",
            h_input[0..4].iter().map(|x| x * 2.0).collect::<Vec<_>>()
        );
        *failed += 1;
    }
}

fn debug_extern_double_global_runner(
    ctx: &Arc<CudaContext>,
    module: &kernels::LoadedModule,
    passed: &mut i32,
    failed: &mut i32,
) {
    println!("--- Test: debug_extern_double_global ---");
    println!("    Testing EXTERN function with GLOBAL memory pointer");

    let num_threads = 4usize;
    let floats_per_thread = 16usize;
    let total_floats = num_threads * floats_per_thread;

    let h_input: Vec<f32> = (0..total_floats)
        .map(|i| (i % floats_per_thread) as f32)
        .collect();

    let stream = ctx.default_stream();
    let d_inout = DeviceBuffer::from_host(&stream, &h_input).unwrap();

    let config = LaunchConfig {
        grid_dim: (1, 1, 1),
        block_dim: (num_threads as u32, 1, 1),
        shared_mem_bytes: 0,
    };

    let inout_ptr = d_inout.cu_deviceptr() as *mut f32;
    module
        .debug_extern_double_global((stream).as_ref(), config, inout_ptr)
        .expect("Kernel launch failed");

    let h_output = d_inout.to_host_vec(&stream).unwrap();

    let mut max_error = 0.0f32;
    for i in 0..total_floats {
        let expected = h_input[i] * 2.0;
        let error = (h_output[i] - expected).abs();
        if error > max_error {
            max_error = error;
        }
    }

    let tolerance = 1e-6;
    if max_error < tolerance {
        println!("    ✓ PASSED (max_error={:.6})", max_error);
        *passed += 1;
    } else {
        println!("    ✗ FAILED (max_error={:.6})", max_error);
        println!(
            "    First few values: input={:?}, output={:?}",
            &h_input[0..4],
            &h_output[0..4]
        );
        *failed += 1;
    }
}

fn debug_extern_double_runner(
    ctx: &Arc<CudaContext>,
    module: &kernels::LoadedModule,
    passed: &mut i32,
    failed: &mut i32,
) {
    println!("--- Test: debug_extern_double ---");
    println!("    Testing EXTERN function with LOCAL memory pointer (Rust kernel)");

    let num_threads = 4usize;
    let floats_per_thread = 16usize;
    let total_floats = num_threads * floats_per_thread;

    let h_input: Vec<f32> = (0..total_floats)
        .map(|i| (i % floats_per_thread) as f32)
        .collect();

    let stream = ctx.default_stream();
    let d_input = DeviceBuffer::from_host(&stream, &h_input).unwrap();
    let d_output = DeviceBuffer::<f32>::zeroed(&stream, total_floats).unwrap();

    let config = LaunchConfig {
        grid_dim: (1, 1, 1),
        block_dim: (num_threads as u32, 1, 1),
        shared_mem_bytes: 0,
    };

    let input_ptr = d_input.cu_deviceptr() as *const f32;
    let output_ptr = d_output.cu_deviceptr() as *mut f32;
    module
        .debug_extern_double((stream).as_ref(), config, input_ptr, output_ptr)
        .expect("Kernel launch failed");

    let h_output = d_output.to_host_vec(&stream).unwrap();

    // Output should be input * 2 (extern function doubles each value)
    let mut max_error = 0.0f32;
    for i in 0..total_floats {
        let expected = h_input[i] * 2.0;
        let error = (h_output[i] - expected).abs();
        if error > max_error {
            max_error = error;
        }
    }

    let tolerance = 1e-6;
    if max_error < tolerance {
        println!("    ✓ PASSED (max_error={:.6})", max_error);
        *passed += 1;
    } else {
        println!("    ✗ FAILED (max_error={:.6})", max_error);
        println!(
            "    First few values: input={:?}, output={:?}",
            &h_input[0..4],
            &h_output[0..4]
        );
        println!(
            "    Expected (input*2): {:?}",
            h_input[0..4].iter().map(|x| x * 2.0).collect::<Vec<_>>()
        );
        *failed += 1;
    }
}

fn test_fft_8_roundtrip_runner(
    ctx: &Arc<CudaContext>,
    module: &kernels::LoadedModule,
    passed: &mut i32,
    failed: &mut i32,
) {
    println!("--- Test: test_fft_8_roundtrip ---");
    println!("    Testing FFT-8 forward + inverse (should recover scaled input)");

    let num_threads = 4usize;
    let complex_per_thread = 8usize;
    let floats_per_thread = complex_per_thread * 2; // real + imag
    let total_floats = num_threads * floats_per_thread;

    // Generate test input: simple pattern
    let h_input: Vec<f32> = (0..total_floats)
        .map(|i| (i % floats_per_thread) as f32)
        .collect();

    let stream = ctx.default_stream();
    let d_input = DeviceBuffer::from_host(&stream, &h_input).unwrap();
    let d_output = DeviceBuffer::<f32>::zeroed(&stream, total_floats).unwrap();

    let config = LaunchConfig {
        grid_dim: (1, 1, 1),
        block_dim: (num_threads as u32, 1, 1),
        shared_mem_bytes: 0,
    };

    let input_ptr = d_input.cu_deviceptr() as *const f32;
    let output_ptr = d_output.cu_deviceptr() as *mut f32;
    module
        .test_fft_8_roundtrip((stream).as_ref(), config, input_ptr, output_ptr)
        .expect("Kernel launch failed");

    let h_output = d_output.to_host_vec(&stream).unwrap();

    // FFT -> IFFT should give input * N (where N=8)
    let scale = 8.0f32;
    let mut max_error = 0.0f32;
    for i in 0..total_floats {
        let expected = h_input[i] * scale;
        let error = (h_output[i] - expected).abs();
        if error > max_error {
            max_error = error;
        }
    }

    let tolerance = 1e-3;
    if max_error < tolerance {
        println!("    ✓ PASSED (max_error={:.6})", max_error);
        *passed += 1;
    } else {
        println!(
            "    ✗ FAILED (max_error={:.6}, tolerance={:.6})",
            max_error, tolerance
        );
        *failed += 1;
    }
}

fn test_fft_16_roundtrip_runner(
    ctx: &Arc<CudaContext>,
    module: &kernels::LoadedModule,
    passed: &mut i32,
    failed: &mut i32,
) {
    println!("--- Test: test_fft_16_roundtrip ---");
    println!("    Testing FFT-16 forward + inverse");

    let num_threads = 4usize;
    let complex_per_thread = 16usize;
    let floats_per_thread = complex_per_thread * 2;
    let total_floats = num_threads * floats_per_thread;

    let h_input: Vec<f32> = (0..total_floats)
        .map(|i| (i % floats_per_thread) as f32)
        .collect();

    let stream = ctx.default_stream();
    let d_input = DeviceBuffer::from_host(&stream, &h_input).unwrap();
    let d_output = DeviceBuffer::<f32>::zeroed(&stream, total_floats).unwrap();

    let config = LaunchConfig {
        grid_dim: (1, 1, 1),
        block_dim: (num_threads as u32, 1, 1),
        shared_mem_bytes: 0,
    };

    let input_ptr = d_input.cu_deviceptr() as *const f32;
    let output_ptr = d_output.cu_deviceptr() as *mut f32;
    module
        .test_fft_16_roundtrip((stream).as_ref(), config, input_ptr, output_ptr)
        .expect("Kernel launch failed");

    let h_output = d_output.to_host_vec(&stream).unwrap();

    let scale = 16.0f32;
    let mut max_error = 0.0f32;
    for i in 0..total_floats {
        let expected = h_input[i] * scale;
        let error = (h_output[i] - expected).abs();
        if error > max_error {
            max_error = error;
        }
    }

    let tolerance = 1e-3;
    if max_error < tolerance {
        println!("    ✓ PASSED (max_error={:.6})", max_error);
        *passed += 1;
    } else {
        println!("    ✗ FAILED (max_error={:.6})", max_error);
        *failed += 1;
    }
}

fn test_gemm_32x32x32_runner(
    ctx: &Arc<CudaContext>,
    module: &kernels::LoadedModule,
    passed: &mut i32,
    failed: &mut i32,
) {
    println!("--- Test: test_gemm_32x32x32 ---");
    println!("    Testing 32x32x32 block-level GEMM: C = A * B");

    let m = 32usize;
    let n = 32usize;
    let k = 32usize;

    // Initialize matrices
    // A: 32x32 row-major (identity-ish for easy verification)
    // B: 32x32 col-major (identity-ish)
    let mut h_a = vec![0.0f32; m * k];
    let mut h_b = vec![0.0f32; k * n];

    // Make A an identity matrix (row-major)
    for i in 0..m.min(k) {
        h_a[i * k + i] = 1.0;
    }

    // Make B an identity matrix (col-major: B[i,j] at index j*k + i)
    for i in 0..k.min(n) {
        h_b[i * k + i] = 1.0;
    }

    let stream = ctx.default_stream();
    let d_a = DeviceBuffer::from_host(&stream, &h_a).unwrap();
    let d_b = DeviceBuffer::from_host(&stream, &h_b).unwrap();
    let d_c = DeviceBuffer::<f32>::zeroed(&stream, m * n).unwrap();

    let smem_bytes = 16 * 1024u32;

    let config = LaunchConfig {
        grid_dim: (1, 1, 1),
        block_dim: (256, 1, 1),
        shared_mem_bytes: smem_bytes,
    };

    let a_ptr = d_a.cu_deviceptr() as *const f32;
    let b_ptr = d_b.cu_deviceptr() as *const f32;
    let c_ptr = d_c.cu_deviceptr() as *mut f32;
    module
        .test_gemm_32x32x32((stream).as_ref(), config, a_ptr, b_ptr, c_ptr)
        .expect("Kernel launch failed");

    let h_c = d_c.to_host_vec(&stream).unwrap();

    // C = I * I = I, so C should be identity matrix
    let mut max_error = 0.0f32;
    for i in 0..m {
        for j in 0..n {
            let expected = if i == j { 1.0 } else { 0.0 };
            let actual = h_c[i * n + j];
            let error = (actual - expected).abs();
            if error > max_error {
                max_error = error;
            }
        }
    }

    let tolerance = 1e-3;
    if max_error < tolerance {
        println!("    ✓ PASSED (max_error={:.6})", max_error);
        *passed += 1;
    } else {
        println!("    ✗ FAILED (max_error={:.6})", max_error);
        // Print a few values for debugging
        println!(
            "    C[0,0]={}, C[1,1]={}, C[0,1]={}",
            h_c[0], h_c[33], h_c[1]
        );
        *failed += 1;
    }
}

fn test_gemm_32x32x32_alphabeta_runner(
    ctx: &Arc<CudaContext>,
    module: &kernels::LoadedModule,
    passed: &mut i32,
    failed: &mut i32,
) {
    println!("--- Test: test_gemm_32x32x32_alphabeta ---");
    println!("    Testing GEMM: C = 2.0 * A * B + 1.0 * C");

    let m = 32usize;
    let n = 32usize;
    let k = 32usize;

    // A = I, B = I (identity matrices)
    let mut h_a = vec![0.0f32; m * k];
    let mut h_b = vec![0.0f32; k * n];
    let mut h_c = vec![0.0f32; m * n];

    for i in 0..m.min(k) {
        h_a[i * k + i] = 1.0;
    }
    for i in 0..k.min(n) {
        h_b[i * k + i] = 1.0;
    }
    // Initialize C with 1.0 on diagonal
    for i in 0..m.min(n) {
        h_c[i * n + i] = 1.0;
    }

    let stream = ctx.default_stream();
    let d_a = DeviceBuffer::from_host(&stream, &h_a).unwrap();
    let d_b = DeviceBuffer::from_host(&stream, &h_b).unwrap();
    let d_c = DeviceBuffer::from_host(&stream, &h_c).unwrap();

    let smem_bytes = 16 * 1024u32;

    let config = LaunchConfig {
        grid_dim: (1, 1, 1),
        block_dim: (256, 1, 1),
        shared_mem_bytes: smem_bytes,
    };

    let alpha = 2.0f32;
    let beta = 1.0f32;

    let a_ptr = d_a.cu_deviceptr() as *const f32;
    let b_ptr = d_b.cu_deviceptr() as *const f32;
    let c_ptr = d_c.cu_deviceptr() as *mut f32;
    module
        .test_gemm_32x32x32_alphabeta((stream).as_ref(), config, alpha, a_ptr, b_ptr, beta, c_ptr)
        .expect("Kernel launch failed");

    let h_result = d_c.to_host_vec(&stream).unwrap();

    // C = 2*I*I + 1*I = 2*I + I = 3*I
    // Diagonal should be 3.0, off-diagonal should be 0.0
    let mut max_error = 0.0f32;
    for i in 0..m {
        for j in 0..n {
            let expected = if i == j { 3.0 } else { 0.0 };
            let actual = h_result[i * n + j];
            let error = (actual - expected).abs();
            if error > max_error {
                max_error = error;
            }
        }
    }

    let tolerance = 1e-3;
    if max_error < tolerance {
        println!("    ✓ PASSED (max_error={:.6})", max_error);
        *passed += 1;
    } else {
        println!("    ✗ FAILED (max_error={:.6})", max_error);
        println!("    C[0,0]={} (expected 3.0)", h_result[0]);
        *failed += 1;
    }
}

// =============================================================================
// libmathdx-generated FFT Test Runner (Option B)
// Only available when the "libmathdx" feature is enabled.
// =============================================================================

/// Test runner for libmathdx-generated 16-point FFT.
///
/// This tests FFT functions that were generated at build time using the libmathdx
/// C API, WITHOUT any hand-written C++ wrapper code.
#[cfg(feature = "libmathdx")]
fn test_libmathdx_fft_16_roundtrip_runner(
    ctx: &Arc<CudaContext>,
    module: &kernels::LoadedModule,
    passed: &mut i32,
    failed: &mut i32,
) {
    println!("--- Test: test_libmathdx_fft_16_roundtrip ---");
    println!("    Testing libmathdx-generated FFT-16 (Option B - no C++ wrappers!)");

    let num_threads = 4usize;
    let complex_per_thread = 16usize;
    let floats_per_thread = complex_per_thread * 2;
    let total_floats = num_threads * floats_per_thread;

    let h_input: Vec<f32> = (0..total_floats)
        .map(|i| (i % floats_per_thread) as f32)
        .collect();

    let stream = ctx.default_stream();
    let d_input = DeviceBuffer::from_host(&stream, &h_input).unwrap();
    let mut d_output = DeviceBuffer::<f32>::zeroed(&stream, total_floats).unwrap();

    let config = LaunchConfig {
        grid_dim: (1, 1, 1),
        block_dim: (num_threads as u32, 1, 1),
        shared_mem_bytes: 0,
    };

    let input_ptr = d_input.cu_deviceptr() as *const f32;
    let output_ptr = d_output.cu_deviceptr() as *mut f32;
    module
        .test_libmathdx_fft_16_roundtrip((stream).as_ref(), config, input_ptr, output_ptr)
        .expect("Kernel launch failed");

    let h_output = d_output.to_host_vec(&stream).unwrap();

    // FFT -> IFFT should give input * N (where N=16)
    let scale = 16.0f32;
    let mut max_error = 0.0f32;
    for i in 0..total_floats {
        let expected = h_input[i] * scale;
        let error = (h_output[i] - expected).abs();
        if error > max_error {
            max_error = error;
        }
    }

    let tolerance = 1e-3;
    if max_error < tolerance {
        println!("    ✓ PASSED (max_error={:.6})", max_error);
        println!("    This FFT was generated by libmathdx C API at build time!");
        *passed += 1;
    } else {
        println!("    ✗ FAILED (max_error={:.6})", max_error);
        *failed += 1;
    }
}
